logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymybuddy_testauth
    username: root
    password: MySQLmdp123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 53dbb74cc6c2e1ca3b73
            client-secret: 74b574986e6a09a59b73fad6f4ef557db6e53e2b
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization-code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization-code
            redirect-uri: "http://localhost:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000